### ISSUE TITLE
compiling error on windows 11

### ISSUE THREAD

**Issue by ghost** [jerous86/nimqt#28] opened 2023-07-16 14:51 UTC
```
C:\Users\faisal\Desktop\nimqt-main\examples>nim cpp hello.nim
Hint: used config file 'C:\nim-1.6.14\config\nim.cfg' [Conf]
Hint: used config file 'C:\nim-1.6.14\config\config.nims' [Conf]
...................................................................................................................................
C:\Users\faisal\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qstring.nim(189, 1) Error: redefinition of 'arg'; previous declaration here: C:\Users\faisal\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qstring.nim(179, 6)
```
```
Device name	DESKTOP-SCHT1LN
Processor	Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
Installed RAM	32.0 GB (31.8 GB usable)
Device ID	956E29D9-BA24-455D-820F-E3BD165E88A4
Product ID	00330-80000-00000-AA491
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎7/‎8/‎2023
OS build	22621.1992
Experience	Windows Feature Experience Pack 1000.22644.1000.0
```

**Comment by jerous86** [comment] 2023-08-04 18:24
Same issue as #30 
cint == clong on windows, but not on other systems. The code to generate qstring.nim has some trouble taking this into account, when there are default values.
Looking into it. A temporary fix is to comment them out.

**Comment by jerous86** [comment] 2023-08-06 23:40
I tracked it down to the fact that naming was inconsistent in qt, while my scripts assumed parameters where identically named.
So I think it should be fixed now.

**Comment by ghost** [comment] 2023-08-07 05:00
> I tracked it down to the fact that naming was inconsistent in qt, while my scripts assumed parameters where identically named. So I think it should be fixed now.

thanks, shall i close this issue?

**Comment by jerous86** [comment] 2023-08-07 06:39
If the issue is resolved for you, then you can close it yes :)

**Closed as completed** 2023-08-07 13:54 UTC
